# Generated by Django 3.2.20 on 2023-07-25 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20230725_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='label_affiliation',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.labelaffiliation'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pro',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.pro'),
        ),
        migrations.AlterField(
            model_name='user',
            name='publisher_affiliation',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.publisheraffiliation'),
        ),
    ]
